### ISSUE TITLE
panic in goreleaser

### ISSUE THREAD

**Issue by lidel** [ipdxco/unified-github-workflows#84]
CI at https://github.com/ipfs/someguy/pull/77#issuecomment-2274401162 errors:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e698f]

goroutine 24 [running]:
go/types.(*Checker).handleBailout(0xc0006cac00, 0xc000ec9c10)
	/opt/hostedtoolcache/go/1.22.5/x64/src/go/types/check.go:367 +0x88
```

running `go install golang.org/x/exp/cmd/gorelease@latest` locally and then `gorelease -base=v0.3.0 -version=v0.4.0` in the PR passed fine:

```
# summary
v0.4.0 is a valid semantic version for this release.
```

@galargh i vaguely remember similar error a while ago, version in github workflow needs to be updated?

**Comment by galargh** [comment]
We have updated the goreleaser to the latest version now. Hope this helps. Let me know if the issue still persists.
